import { format } from 'date-fns';
import { X, Tag } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { Invoice } from '@/types/invoice';

interface InvoiceHeaderProps {
  invoice: Invoice;
  onClose: () => void;
}

const getStatusColor = (status: string) => {
  switch (status) {
    case 'DRAFT':
      return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300';
    case 'SENT':
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-300';
    case 'PAID':
      return 'bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-300';
    case 'OVERDUE':
      return 'bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-300';
    case 'CANCELLED':
      return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300';
    default:
      return 'bg-gray-100 text-gray-800';
  }
};

export function InvoiceHeader({ invoice, onClose }: InvoiceHeaderProps) {
  const isAutoGenerated = invoice.summary?.entryCount !== undefined && invoice.summary.entryCount > 0;
  const hasProject = invoice.project !== undefined;

  return (
    <div className="space-y-3 pb-4 border-b">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-sm text-muted-foreground mb-1">Invoice Details</h2>
          <h1 className="text-3xl font-bold">{invoice.invoiceNumber}</h1>
        </div>
        <div className="flex items-center gap-2">
          <Badge className={getStatusColor(invoice.status)}>
            {invoice.status}
          </Badge>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="w-4 h-4" />
          </Button>
        </div>
      </div>

      <div className="flex items-center gap-3 text-sm text-muted-foreground">
        <span>Created {format(new Date(invoice.createdAt), 'PPP')}</span>
        {hasProject && (
          <Badge variant="outline" className="gap-1">
            <Tag className="w-3 h-3" />
            Project-linked
          </Badge>
        )}
        {isAutoGenerated && (
          <Badge variant="outline" className="gap-1">
            Auto-generated
          </Badge>
        )}
      </div>
    </div>
  );
}
